# This file was *autogenerated* from the file hist.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_255 = Integer(255); _sage_const_1000 = Integer(1000)
import cv2
import numpy
from matplotlib import image
img=cv2.imread('/home/amarjeet/projects/python/pictures/triangle.png')
img=img.astype('uint8')
x,y,r=img.shape
img=cv2.blur(img,(_sage_const_7 ,_sage_const_7 ))
img=img.astype('float32')
Y=img[:,:,_sage_const_0 ]+img[:,:,_sage_const_1 ]+img[:,:,_sage_const_2 ]
R=img[:,:,_sage_const_0 ]/Y
G=img[:,:,_sage_const_1 ]/Y
R=R*_sage_const_255 
G=G*_sage_const_255 
R=R.astype('uint8')
G=G.astype('uint8')
a=numpy.ndarray(shape=(x,y))
a=(R+_sage_const_1000 *G)
a=a.astype('int')
x,y=a.shape
color=[]
tr = -_sage_const_1 
count=_sage_const_0 
for r in range(x) :
	for b in range(y):
		color.append(a[r][b])
	
color.sort()
print(color)
no_colors=[]
value_colors=[]
b=_sage_const_0 
c=_sage_const_0 
for r in color:
	if(tr!=r):
		count=count+_sage_const_1 
		value_colors.append(tr)
		no_colors.append(b)
		tr=r
		b=_sage_const_0 
	b=b+_sage_const_1 
no_colors.append(b)
value_colors.append(tr)
print(value_colors)
print(count)
first=_sage_const_0 
second=_sage_const_0 
max=[]
b=-_sage_const_1 
min=[]
for third in no_colors:
	if(second>=first and second >third):
		max.append(value_colors[b])
	if(second<=first and second<third):
		min.append(value_colors[b])
	first=second
	second=third
	b=b+_sage_const_1 
if(second>first):
	max.append(value_colors[b])
else:
	max.append(value_colors[b])
print(len(min),len(max))


